apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  description: P1-5 isOptional via v2 yaml
  name: sj-bp
  project: shobhit
spec:
  base:
    name: minimal
    version: 4.3.1
  customAddons:
  - name: sj-addon1
    version: v3
  - name: sj-addon2
    version: v3
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator:
        discovery: {}
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer:
        enabled: true
      nodeExporter:
        enabled: true
      prometheusAdapter:
        enabled: true
      resources: {}
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: phani-p2
  type: custom
  version: v2yaml-test
  versionState: active
