apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: sj-bp
  project: shobhit
spec:
  base:
    name: minimal
    version: 4.3.1
  componentsCriticality:
  - name: sj-addon2
  - name: sj-addon1
  customAddons:
  - isOptional: true
    name: sj-addon1
    version: v1
  - isOptional: true
    name: sj-addon2
    version: v1
  defaultAddons:
    enableIngress: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: draft
