apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    cli: eks
  name: cli-eksrauto-193302671
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: cli-cprauto-193302671
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: kalyan-rafay
        principalARN: arn:aws:iam::679196758854:user/kalyan@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: rauto-entry
        principalARN: arn:aws:iam::679196758854:user/chaitanya@rafay.co
        type: STANDARD
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    iam:
      serviceAccounts:
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-irsa
          labels:
            irsalabel: rauto-irsalabel
          name: rauto-irsa
          namespace: rafay-system
        tags:
          irsatag: rauto-irsatag
      withOIDC: true
    metadata:
      name: cli-eksrauto-193302671
      region: us-east-1
      tags:
        build_num: dev-master-496
        creation_time: "2026-10-10T06:57:30Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
        tags-day2: eks-tags-day-2-test
      version: "1.32"
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-first-193302671
      privateNetworking: true
      version: "1.32"
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-second-193302671
      privateNetworking: true
      version: "1.32"
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
