apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-956701154
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: cli-cprauto-956701154
  config:
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      withOIDC: true
    kubernetesNetworkConfig:
      ipFamily: IPv6
    managedNodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-first-956701154
      privateNetworking: true
      version: "1.34"
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-second-956701154
      privateNetworking: true
      version: "1.34"
    metadata:
      name: cli-eksrauto-956701154
      region: us-east-1
      tags:
        build_num: dev-master-496
        creation_time: "2026-10-10T10:06:33Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
      version: "1.34"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      subnets:
        private:
          subnet-00961c49c9576acef:
            id: subnet-00961c49c9576acef
          subnet-0e7df66bf00bd4a9a:
            id: subnet-0e7df66bf00bd4a9a
        public:
          subnet-0842a03c6d89162f6:
            id: subnet-0842a03c6d89162f6
          subnet-0aa1d5423962d5a02:
            id: subnet-0aa1d5423962d5a02
  type: aws-eks
