apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-windows179883387
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: cli-cprauto-179883387
  config:
    accessConfig:
      authenticationMode: API_AND_CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    iam:
      serviceAccounts:
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-irsa
          labels:
            irsalabel: rauto-irsalabel
          name: rauto-irsa
          namespace: rafay-system
        roleOnly: true
        tags:
          irsatag: rauto-irsatag
      withOIDC: true
    identityMappings:
      arns:
      - arn: arn:aws:iam::679196758854:user/automation-qa
        group:
        - system:masters
        username: automation
    managedNodeGroups:
    - ami: ami-0a5ac143a9a02d0e9
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: custom-managed-Bottlerocket-179883387
      overrideBootstrapCommand: '| [Bottlerocket]'
      privateNetworking: true
      tags:
        email: automation-user@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: ng-managed-default-Bottlerocket-179883387
      privateNetworking: true
      tags:
        email: automation-user@rafay.co
        env: automation
      version: "1.35"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: cli-eksrauto-windows179883387
      region: us-east-1
      tags:
        build_num: dev-master-496
        creation_time: "2026-10-10T04:31:42Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
      version: "1.35"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - ami: ami-0a5ac143a9a02d0e9
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: custom-self-managed-Bottlerocket-179883387
      overrideBootstrapCommand: '| [Bottlerocket]'
      privateNetworking: true
      tags:
        email: automation-user@rafay.co
        env: automation
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: ng-selfmanaged-default-Bottlerocket-179883387
      privateNetworking: true
      tags:
        email: automation-user@rafay.co
        env: automation
      version: "1.35"
      volumeSize: 80
      volumeType: gp3
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: add-ng-selfmanaged-default-Bottlerocket-179883387
      privateNetworking: true
      tags:
        email: automation-user@rafay.co
        env: automation
      version: "1.35"
      volumeSize: 80
      volumeType: gp3
    secretsEncryption:
      encryptExistingSecrets: true
      keyARN: arn:aws:kms:us-east-1:211125364662:key/d30cd169-de6e-43e5-9f06-0a8eab64c2d8
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
