apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-628609647
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: cprauto-628609647
  config:
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    managedNodeGroups:
    - instanceTypes:
      - t3a.xlarge
      - t3.xlarge
      name: cli-awsngrauto-628609647
      privateNetworking: true
      spot: true
      version: "1.36"
    metadata:
      name: cli-eksrauto-628609647
      region: us-east-1
      tags:
        build_num: dev-master-494
        creation_time: "2026-10-09T18:29:13Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
      version: "1.36"
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instancesDistribution:
        instanceTypes:
        - t3a.xlarge
        - t3.xlarge
        maxPrice: 0.7
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2
      name: cli-selfngrauto-628609647
      privateNetworking: true
      version: "1.36"
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instancesDistribution:
        instanceTypes:
        - t3.xlarge
        - t3a.xlarge
        maxPrice: 0.75
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: lowest-price
        spotInstancePools: 3
      name: eksng2rauto-2701000
      privateNetworking: true
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
    zonalShiftConfig:
      enabled: true
  type: aws-eks
