apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    cli: eks
  name: cli-eksrauto-147154185
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: cli-cprauto-147154185
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: kalyan-rafay
        principalARN: arn:aws:iam::679196758854:user/kalyan@rafay.co
        type: STANDARD
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSViewPolicy
        kubernetesUsername: rauto-entry
        principalARN: arn:aws:iam::679196758854:user/chaitanya@rafay.co
        type: STANDARD
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: eks-pod-identity-agent
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    - name: amazon-cloudwatch-observability
      version: latest
    - name: aws-guardduty-agent
      version: latest
    - name: eks-node-monitoring-agent
      version: latest
    - name: aws-network-flow-monitoring-agent
      version: latest
    - name: aws-efs-csi-driver
      version: latest
    - name: snapshot-controller
      version: latest
    - name: aws-mountpoint-s3-csi-driver
      version: latest
    - name: adot
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    iam:
      serviceAccounts:
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-irsa
          labels:
            irsalabel: rauto-irsalabel
          name: rauto-irsa
          namespace: rafay-system
        tags:
          irsatag: rauto-irsatag
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-8
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-5
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-6
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-9
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-10
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-1
          namespace: namespace-65512118
        roleOnly: false
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-2
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-3
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-4
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      - attachPolicy: {}
        attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        metadata:
          annotations:
            irsa: rauto-65512118
          labels:
            irsalabel: rauto-65512118
          name: rauto-sa-4095-7
          namespace: namespace-65512118
        tags:
          irsatag: rauto-65512118
      withOIDC: true
    managedNodeGroups:
    - amiFamily: Bottlerocket
      bottlerocket:
        enableAdminContainer: false
        settings:
          pki:
            my-trusted-bundle:
              data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdUakNDQlRhZ0F3SUJBZ0lUWUFBQUFDTi91dnZiMUNRbEhnQUFBQUFBSXpBTkJna3Foa2lHOXcwQkFRc0YKQURCZU1STXdFUVlLQ1pJbWlaUHlMR1FCR1JZRFkyOXRNUmN3RlFZS0NaSW1pWlB5TEdRQkdSWUhabUZqZEhObApkREVTTUJBR0NnbVNKb21UOGl4a0FSa1dBbkJqTVJvd0dBWURWUVFERXhGR1lXTjBVMlYwVUc5c2FXTjVNMEV3Ck1UQWVGdzB5TURBeE1EZ3hOVEV6TWpGYUZ3MHlOVEF4TURZeE5URXpNakZhTUYweEV6QVJCZ29Ka2lhSmsvSXMKWkFFWkZnTmpiMjB4RnpBVkJnb0praWFKay9Jc1pBRVpGZ2RtWVdOMGMyVjBNUkl3RUFZS0NaSW1pWlB5TEdRQgpHUllDY0dNeEdUQVhCZ05WQkFNVEVFWmhZM1JUWlhSSmMzTjFaVE5CTURFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEU0w4dFJJcnoxZlFhUVBINWZuUEVrbS9DcXNHRlRFajZXaVdYTmVrTmQKMjN1VHo1Qlk0bXJCOWJVdzVuMDZPRDIzTzJFbEV6NGtSUXVaK3FlSjBxVU11dlQ4bERZb3lnSnpkTElzSHFRNwpqSkxFZnkxUmx6V0NRbko1WThvWFVyUTMybmt4T1FiQUpQUC9YNFJLUFdrY2hJOThvVVQ4SXh0dlJNV2MxNThpCjVPZ0dXZ2V0NFc5dSt1UHFnSDk3bzFLMTEvMGFjY1h2SDl4eFZTZFFCdEdDeVVaT3EvRU14RFZrUlI2b0JnbUYKdVI5cUl4b0Jqd2U3TEcxTzROMHVDUS9jOFZRWkF3MFh3bURqTHBhbWtaUnpyK3laLzVlOHZWeE51c1gxcjlwagpwUERxb09XbTNKeWFjZDF2VFowUVBveGdHVENEaUROZmNJek9hRkRkNC9jZEFnTUJBQUdqZ2dNRU1JSURBREFRCkJna3JCZ0VFQVlJM0ZRRUVBd0lCQVRBakJna3JCZ0VFQVlJM0ZRSUVGZ1FVMkk0SnQrU2k0US9VZ01zWE1ZUVAKZ1FiSDZxVXdIUVlEVlIwT0JCWUVGRUpieWJFWDhFTGRCTEU1WWNFKzk3cDV2TEJtTUJrR0NTc0dBUVFCZ2pjVQpBZ1FNSGdvQVV3QjFBR0lBUXdCQk1Bc0dBMVVkRHdRRUF3SUJoakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjhHCkExVWRJd1FZTUJhQUZDamoySXVlclE4U216REovZVE4bGJNQXdMT1BNSUlCR2dZRFZSMGZCSUlCRVRDQ0FRMHcKZ2dFSm9JSUJCYUNDQVFHR2djVnNaR0Z3T2k4dkwwTk9QVVpoWTNSVFpYUlFiMnhwWTNrelFUQXhMRU5PUFZCTApTUzFRVDB4SlExa3pRVEF4TEVOT1BVTkVVQ3hEVGoxUWRXSnNhV01sTWpCTFpYa2xNakJUWlhKMmFXTmxjeXhEClRqMVRaWEoyYVdObGN5eERUajFEYjI1bWFXZDFjbUYwYVc5dUxFUkRQWEJqTEVSRFBXWmhZM1J6WlhRc1JFTTkKWTI5dFAyTmxjblJwWm1sallYUmxVbVYyYjJOaGRHbHZia3hwYzNRL1ltRnpaVDl2WW1wbFkzUkRiR0Z6Y3oxagpVa3hFYVhOMGNtbGlkWFJwYjI1UWIybHVkSVkzYUhSMGNEb3ZMM0JyYVM1bVlXTjBjMlYwTG1OdmJTOURaWEowClJXNXliMnhzTDBaaFkzUlRaWFJRYjJ4cFkza3pRVEF4TG1OeWJEQ0NBUzRHQ0NzR0FRVUZCd0VCQklJQklEQ0MKQVJ3d2diWUdDQ3NHQVFVRkJ6QUNob0dwYkdSaGNEb3ZMeTlEVGoxR1lXTjBVMlYwVUc5c2FXTjVNMEV3TVN4RApUajFCU1VFc1EwNDlVSFZpYkdsakpUSXdTMlY1SlRJd1UyVnlkbWxqWlhNc1EwNDlVMlZ5ZG1salpYTXNRMDQ5ClEyOXVabWxuZFhKaGRHbHZiaXhFUXoxd1l5eEVRejFtWVdOMGMyVjBMRVJEUFdOdmJUOWpRVU5sY25ScFptbGoKWVhSbFAySmhjMlUvYjJKcVpXTjBRMnhoYzNNOVkyVnlkR2xtYVdOaGRHbHZia0YxZEdodmNtbDBlVEJoQmdncgpCZ0VGQlFjd0FvWlZhSFIwY0RvdkwzQnJhUzVtWVdOMGMyVjBMbU52YlM5RFpYSjBSVzV5YjJ4c0wxQkxTUzFRClQweEpRMWt6UVRBeExuQmpMbVpoWTNSelpYUXVZMjl0WDBaaFkzUlRaWFJRYjJ4cFkza3pRVEF4TG1OeWREQU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcjIzYmtTbWFQRlEzU1d4U1RocUdjaXNKbFRzTncxenJtWXFMZ1RBdApqUUVKakd2NkNneEE2MU9lS2J2RTZGU3BUY01CWUxFMlJicno3T2xNV1pJb2xMdzJtSytoOVJVUVNrNklJU04xCmJ1QXVJM0tkckVvdDNRbDNuM0krYlB4ODhnR3lxYXJwOHE2YmJHZmpwVzgzZ1dJckJrck9KM05xV2dlRTRTbW0KSU5IK1RBWjB0U29uQUx0K1p3bnVRZjU4ZTR4dnN5VitoZ0VJc2ZZRUlHQTFMOUZ3cHp2cWJQWDlVZVk3eGdsQQpibFJqUVY0ajJvZVB6b1RPZFBYeXI4Q3dIcHM1Y0NMbHA1WkpOV3haYm1Ed25iT2UwTm1waUoxVjRUbWVoRmlWCjU4VU40aFJjWTZEVTF1SHp2cjlaWjdkMUg1ckdWcW1KOUJCM3B5SGRwMW9Zc0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlHVGpDQ0JUYWdBd0lCQWdJVFlBQUFBQ0pwYjQzR3hUSnNvZ0FBQUFBQUlqQU5CZ2txaGtpRzl3MEJBUXNGCkFEQmVNUk13RVFZS0NaSW1pWlB5TEdRQkdSWURZMjl0TVJjd0ZRWUtDWkltaVpQeUxHUUJHUllIWm1GamRITmwKZERFU01CQUdDZ21TSm9tVDhpeGtBUmtXQW5Cak1Sb3dHQVlEVlFRREV4RkdZV04wVTJWMFVHOXNhV041TTBFdwpNVEFlRncweU1EQXhNRGd4TlRBeU1qQmFGdzB5TlRBeE1EWXhOVEF5TWpCYU1GMHhFekFSQmdvSmtpYUprL0lzClpBRVpGZ05qYjIweEZ6QVZCZ29Ka2lhSmsvSXNaQUVaRmdkbVlXTjBjMlYwTVJJd0VBWUtDWkltaVpQeUxHUUIKR1JZQ2NHTXhHVEFYQmdOVkJBTVRFRVpoWTNSVFpYUkpjM04xWlROQ01ERXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRHNPbjZMVTBxekdMeUUvOW9Ic3R0bmdtN1RBVzdhcjdEc1dxMjF0TzRqClhvcjBKSkUzYzVlenJWOENQRWh3TnREYVNlanNIbm9wUWxRcEJlYUJWdE9lMWFLOEtHVjkxbDlTUGs2VWc0Nm0KQTdtQTVqdEFYSHBxaXNGdHYyZTJoMVlWZkRwWUloeTQ1dTIvTk96aXhBWDFrT3RMSWVnNGJOOXNmSGl2eHNvZwo2akFKTEFSd3Q3QlFocysvWUxPNkdsVzZtUUxYSXo5SmU5Zm5jNW4rZEhkV2F2TkluUFFFR1NFSUVuY0lhQWx3CkxNcmc0MjZPc1lMbXh4a0prWWp6ZEpMSUlpd0VBY1dFYlFlcFlubExpTWVvUUhyV0c0MHNrT0pPOGVnZmZHd0gKL3VSNjZxcWVKWTVHNFgwZzdoRW5uTHpVVk90NG1heSt6U0RDZUUyb1dyWmhBZ01CQUFHamdnTUVNSUlEQURBUQpCZ2tyQmdFRUFZSTNGUUVFQXdJQkFUQWpCZ2tyQmdFRUFZSTNGUUlFRmdRVTdERXhJc24xOUlkK1NFVk9OZHRaCmRUdUUvQ1V3SFFZRFZSME9CQllFRkZtdnpCT0dkdFA2LzVXak1MMlQvcXRPZEhrOU1Ca0dDU3NHQVFRQmdqY1UKQWdRTUhnb0FVd0IxQUdJQVF3QkJNQXNHQTFVZER3UUVBd0lCaGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUI4RwpBMVVkSXdRWU1CYUFGQ2pqMkl1ZXJROFNtekRKL2VROGxiTUF3TE9QTUlJQkdnWURWUjBmQklJQkVUQ0NBUTB3CmdnRUpvSUlCQmFDQ0FRR0dnY1ZzWkdGd09pOHZMME5PUFVaaFkzUlRaWFJRYjJ4cFkza3pRVEF4TEVOT1BWQkwKU1MxUVQweEpRMWt6UVRBeExFTk9QVU5FVUN4RFRqMVFkV0pzYVdNbE1qQkxaWGtsTWpCVFpYSjJhV05sY3l4RApUajFUWlhKMmFXTmxjeXhEVGoxRGIyNW1hV2QxY21GMGFXOXVMRVJEUFhCakxFUkRQV1poWTNSelpYUXNSRU05ClkyOXRQMk5sY25ScFptbGpZWFJsVW1WMmIyTmhkR2x2Ymt4cGMzUS9ZbUZ6WlQ5dlltcGxZM1JEYkdGemN6MWoKVWt4RWFYTjBjbWxpZFhScGIyNVFiMmx1ZElZM2FIUjBjRG92TDNCcmFTNW1ZV04wYzJWMExtTnZiUzlEWlhKMApSVzV5YjJ4c0wwWmhZM1JUWlhSUWIyeHBZM2t6UVRBeExtTnliRENDQVM0R0NDc0dBUVVGQndFQkJJSUJJRENDCkFSd3dnYllHQ0NzR0FRVUZCekFDaG9HcGJHUmhjRG92THk5RFRqMUdZV04wVTJWMFVHOXNhV041TTBFd01TeEQKVGoxQlNVRXNRMDQ5VUhWaWJHbGpKVEl3UzJWNUpUSXdVMlZ5ZG1salpYTXNRMDQ5VTJWeWRtbGpaWE1zUTA0OQpRMjl1Wm1sbmRYSmhkR2x2Yml4RVF6MXdZeXhFUXoxbVlXTjBjMlYwTEVSRFBXTnZiVDlqUVVObGNuUnBabWxqCllYUmxQMkpoYzJVL2IySnFaV04wUTJ4aGMzTTlZMlZ5ZEdsbWFXTmhkR2x2YmtGMWRHaHZjbWwwZVRCaEJnZ3IKQmdFRkJRY3dBb1pWYUhSMGNEb3ZMM0JyYVM1bVlXTjBjMlYwTG1OdmJTOURaWEowUlc1eWIyeHNMMUJMU1MxUQpUMHhKUTFrelFUQXhMbkJqTG1aaFkzUnpaWFF1WTI5dFgwWmhZM1JUWlhSUWIyeHBZM2t6UVRBeExtTnlkREFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXp1ZGtTVDl5OGtJV3ZxU3U3N28zTEpaS0JZQ3FOYWpURkp3UDVkNFEKa09JT3FkWG85YjBZTGs1Qkpaam5aS2xQeUFraUREK3kvMTIvTnJBR1V3TDQxYU5lRFg3NTM1RlpzdEh5YVRkUQo4c3FpRTJCY0hyM0g0TldwcU9Fa3UzaDdqamk1all6M255TnhVMWxyak5Lc3dwNVJQaG9HRnJka1Njd3l2QWxoCjE2OG9wc3lRWG56WjdkYzRkeDNuSTFveVh3U0FBNFpBa3NjaUtEMEcxckZyVmNPTm52U2RpRUdPbzFCRFloOG4KbG10K2c4ZkZua2o2M3ljMmhrUGNlTXRWMnBUbnd2c0YyR2MxZ0pIU05xVHQxaVlwRjh4TFFIbEVnUnR3SHAySgpUT0lDK25DNGhOend4U3hianBNaU1MMHpYelhzWSt6b3FXcUJXVTRZVXBRYWl3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRU96Q0NBeU9nQXdJQkFnSVRMUUFBQUFMak52RmVPRy9lYndBQUFBQUFBakFOQmdrcWhraUc5dzBCQVFzRgpBREFaTVJjd0ZRWURWUVFERXc1R1lXTjBVMlYwVW05dmRFTkJNekFlRncweE5UQTJNVEF5TURNNE5UaGFGdzB5Ck5UQTJNVEF5TURRNE5UaGFNRjR4RXpBUkJnb0praWFKay9Jc1pBRVpGZ05qYjIweEZ6QVZCZ29Ka2lhSmsvSXMKWkFFWkZnZG1ZV04wYzJWME1SSXdFQVlLQ1pJbWlaUHlMR1FCR1JZQ2NHTXhHakFZQmdOVkJBTVRFVVpoWTNSVApaWFJRYjJ4cFkza3pRVEF4TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyVk9KCk8rSVFwenZTRVZDWEhwSmNVR1lReE1XYitqWEF2c0pkdHJ2VlloTFdBSGR2c3MzOU84QzcxN08rQTdzNmlzaHoKa2gzVnArOGkrWDV6dk1hSTRqSTNtUWpyanFVWGFseGN5L2R3bkdoeWxPL1UzQ3lNTXVXR1pvK2lQaElsbGtXdwpoaDl2dDlBbkQ3YmpNT2pMNGpVdHJBRjJvSGRTT2dHaC84cndkaURaZDBIWDFVZzFMb2tpR00yaFdmODhSdEN0CjQ3Q2diQytvbFh0TzRqWjU1RHVsZEFDVVBYR0RXZjgxYXd3WmtiWEg1OEx0TW11aFZISEpDUFk2NlQ0dUZia2cKTkxVVlpKNWVYYi9UNlI1cTV0Sy9LZXZ1aTkzdDNxbFB2N01lQmdYUE5mZEc1eit0M0RDeFduUXM0T2IxSHNDRApZdGRzM2lBbjJzekh3ZStFUXdJREFRQUJvNElCTlRDQ0FURXdFQVlKS3dZQkJBR0NOeFVCQkFNQ0FRQXdIUVlEClZSME9CQllFRkNqajJJdWVyUThTbXpESi9lUThsYk1Bd0xPUE1Ca0dDU3NHQVFRQmdqY1VBZ1FNSGdvQVV3QjEKQUdJQVF3QkJNQXNHQTFVZER3UUVBd0lCaGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUI4R0ExVWRJd1FZTUJhQQpGTkt4QUFpVDZFMklDWFM1bmpiVEw3R1d4QjFZTUVVR0ExVWRId1ErTUR3d09xQTRvRGFHTkdoMGRIQTZMeTl3CmEya3VabUZqZEhObGRDNWpiMjB2UTJWeWRFVnVjbTlzYkM5R1lXTjBVMlYwVW05dmRFTkJNeTVqY213d1hRWUkKS3dZQkJRVUhBUUVFVVRCUE1FMEdDQ3NHQVFVRkJ6QUNoa0ZvZEhSd09pOHZjR3RwTG1aaFkzUnpaWFF1WTI5dApMME5sY25SRmJuSnZiR3d2VUV0SkxWSlBUMVF6UVRBeFgwWmhZM1JUWlhSU2IyOTBRMEV6TG1OeWREQU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBUUVBS1BNUDk0cFNmYUNoS2Fab0NBcWJXcjJ6OG51S0pmVlpzU1hmNDZHT2I2L2oKeWhGVkg1MjJ1UVpOZHc1dmtCakFRQzlrTEtNQ1hFclhEem1paUR4OVltaDZBbEcxMXVLbTh2YTBUdlNFL1pXVQprQVcvVDJPQ3pOU3Z6cGYrbERGa01zUWJaNkVJNUgvZUdCR3l2M0Z2aVRRbVFPSmd3OWV1Z054WTNjaFV0N3J3CnBnWStXb0ptY2d1d2dZUlZBR040SW0yS1NFNkVaMXltRnNxSDZrdEp3QkxOYnl3d1RPRkRabHl6aG9pQllGb3QKN3hmRUVGRmpCMU9PdDR0R3dldTZheXBtWFJGcUNldTB3V0dDK1RsMmhkczVMT1dncWszSzE5ZzNuWHYxaVZQbwpETVBzU3Y4aGVqY2hmTCtXdzJ5OWIzbHZ1MEU5VGtlQ3Y0d0piL0UyYUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERFRDQ0FmV2dBd0lCQWdJUVdBTlFmRmdoQTRsSGk2a29ONmhDK2pBTkJna3Foa2lHOXcwQkFRc0ZBREFaCk1SY3dGUVlEVlFRREV3NUdZV04wVTJWMFVtOXZkRU5CTXpBZUZ3MHhOVEEyTVRBeU1ESXpOVFJhRncwek5UQTIKTVRBeU1ETXpOVE5hTUJreEZ6QVZCZ05WQkFNVERrWmhZM1JUWlhSU2IyOTBRMEV6TUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdlVUa05lZHMrdzlGOVVRQkJjNjhFNFhWalRKSEErRWxWOVNqCmRuaGcrTDh1d0NWaTZweldCT1YvRkVzRWE3bGFNMFdCcjlDeUQ2Z1FaSmRadEdjclpqQU5NV2NBdnE5WUIrNGEKWTQ2aG9mNkFrZzBWNWdkeTZ4emNSN05KSElYbWUrWWxEcU13MHhtVXB4VW1MWldUeFlOUmFmSlpkQVJXZ2R0QgpJVzZVWVZZdDl4MWczcG9WOU9OQ2ptZVlucWtkTXhmOVVQaEdKNjRFR2VYc2lMSXhtc0tHZEpuR1ZHb3hQVGpkCmtuRjgrQjkvNVhpV3hlSE9EOUNmVWxBYktYMkdQTFR2QnpmYkNqeHNKWE05MXpDMTBMTW85Z250cTMyUTNNMjgKZWZiSWxWc2VPZTlQRUlHMVc4bFNaYko4aUd0Q3RpVnRnVWNYbEJVZzFMaHFsd2tJR3dJREFRQUJvMUV3VHpBTApCZ05WSFE4RUJBTUNBWVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVMHJFQUNKUG9UWWdKCmRMbWVOdE12c1piRUhWZ3dFQVlKS3dZQkJBR0NOeFVCQkFNQ0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUxobEtEUEpaSEFQdExQQ1FtaUk3M0VyM0VuSGdLTUhIbXJ6ZWJIQWQrT05KQUROc1J0aHk0NzBOT2F1azZjUwoyYWJ0WWdvZ3N2NkF3YVBXODE2K085UitCNDJkbU1ZYWdNcGliNXFYdkFNOXNrTitSMEdaakRkeUxzOEtEOHBZCk9sUHFsZXRDaC9NdjlHbE9YdVJiM1VudFdWUlRJbEF1ZWQyTm9iR21PcHNDcW5wOWdxT2NiZEdsdXNlVkJ3eWQKeTZ6ZFhBakdZeDBkd2UydkVvYSszbUw4SnZ6UW1XMDdiTmx3NXBuWlRDb2Job3B5TytzeE5TVkdGL3Zvc3IvdgpZbWY5WUpySXMwY3lrd0Zxd2xWcmZmMnFvalBhbGgxWGJOcCtsUGFZL0hjS2RtMDFDRUpSdnhKNHBhSDdEemJxCk5rZmZ3bnExY09tczJqNkZCOFhPcjNvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
              trusted: true
      desiredCapacity: 1
      iam:
        withAddonPolicies:
          autoScaler: true
      instanceTypes:
      - t3.xlarge
      maxSize: 2
      minSize: 0
      name: cli-managedngrauto-147154185
      nodeRepairConfig:
        enabled: true
        maxParallelNodesRepairedPercentage: 10
        maxUnhealthyNodeThresholdPercentage: 20
        nodeRepairConfigOverrides:
        - minRepairWaitTimeMins: 20
          nodeMonitoringCondition: NetworkingReady
          nodeUnhealthyReason: ContainerRuntimeFailed
          repairAction: Replace
        - minRepairWaitTimeMins: 10
          nodeMonitoringCondition: Ready
          nodeUnhealthyReason: ContainerRuntimeFailed
          repairAction: Replace
      privateNetworking: true
      version: "1.35"
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: cli-eksrauto-147154185
      region: us-east-1
      tags:
        build_num: dev-master-494
        creation_time: "2026-10-09T12:04:44Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
      version: "1.36"
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-first-147154185
      privateNetworking: true
      tags:
        key1: value1
        key2: value2
      version: "1.36"
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-second-147154185
      privateNetworking: true
      version: "1.36"
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
