apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cli-eksrauto-958816327
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
  cloudCredentials: cli-cprauto-958816327
  config:
    addons:
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    iam:
      withOIDC: true
    kubernetesNetworkConfig:
      ipFamily: IPv6
    managedNodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-first-958816327
      privateNetworking: true
      version: "1.34"
    - amiFamily: AmazonLinux2023
      desiredCapacity: 1
      instanceType: t3.xlarge
      maxSize: 1
      minSize: 1
      name: cli-ngrauto-second-958816327
      privateNetworking: true
      version: "1.34"
    metadata:
      name: cli-eksrauto-958816327
      region: us-east-1
      tags:
        build_num: dev-master-494
        creation_time: "2026-10-09T11:56:52Z"
        email: automation-user@rafay.co
        env: automation
        squad: dev
      version: "1.34"
    network:
      cni:
        name: aws-cni
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      subnets:
        private:
          subnet-047e2db407f5270a0:
            id: subnet-047e2db407f5270a0
          subnet-048accddf69272c7b:
            id: subnet-048accddf69272c7b
        public:
          subnet-0db1feb1de08be85b:
            id: subnet-0db1feb1de08be85b
          subnet-0f32b0481d5b35b7b:
            id: subnet-0f32b0481d5b35b7b
  type: aws-eks
