apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: eks-cluster-v1-second
  project: defaultproject
spec:
  blueprintConfig:
    name: rishabh-latest-bp
    optionalAddons:
    - simple-addon
    - hello-addon
    version: v2
  cloudCredentials: shobhit_aws
  config:
    metadata:
      name: eks-cluster-v1-second
      region: us-west-1
      version: "1.35"
    nodeGroups:
    - name: ng-1
  type: aws-eks
