apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: gke-tf-1
  project: defaultproject
spec:
  blueprint:
    name: new-blueprint
    optionalAddons:
    - simple-addon
    version: v1
  cloudCredentials: shobhit_gcp
  config:
    controlPlaneVersion: "1.35"
    features:
      enableComputeEnginePersistentDiskCSIDriver: true
    gcpProject: dev-382813
    location:
      config:
        zone: us-central1-c
      type: zonal
    network:
      access:
        config: null
        type: public
      enableVPCNativetraffic: true
      maxPodsPerNode: 110
      name: default
      subnetName: default
    nodePools:
    - machineConfig:
        bootDiskSize: 100
        bootDiskType: pd-standard
        imageType: COS_CONTAINERD
        machineType: e2-standard-4
      management:
        autoUpgrade: true
      name: np-1
      nodeVersion: "1.35"
      size: 2
      upgradeSettings:
        config:
          maxUnavailable: 1
        strategy: SURGE
    releaseChannel:
      channel: REGULAR
  type: gke
