apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: mks-cluster-v3
  project: defaultproject
spec:
  blueprint:
    name: rishabh-latest-bp
    optionalAddons:
    - hello-addon
    - nginx-yaml
    - simple-addon
    version: v2
  config:
    autoApproveNodes: true
    installerTtl: 365
    kubernetesVersion: v1.35.4
    network:
      cni:
        name: Calico
        version: 3.32.0
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: x86_64
      hostname: mks-cluster-v3
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.87
      roles:
      - Worker
      - ControlPlane
      ssh:
        ipAddress: 137.131.4.154
        port: "22"
        privateKeyPath: /Users/rishabh/Downloads/mks-cluster-v3.pem
        username: ubuntu
    platformVersion: v1.3.0
  proxy: {}
  type: mks
