apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    labels: ""
  name: mks-cluster
  project: defaultproject
spec:
  blueprint:
    name: rishabh-latest-bp
    version: v2
  config:
    installerTtl: 365
    kubernetesVersion: v1.35.0
    location: sanjose-us
    network:
      cni:
        name: Calico
        version: 3.32.2
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    platformVersion: v1.4.0
  type: mks
