apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rautocdktf-eks-785894
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rautocdktf-cloudp-785894
  config:
    accessConfig:
      accessEntries:
      - accessPolicies:
        - accessScope:
            type: cluster
          policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
        kubernetesUsername: rauto-tf-user
        principalARN: arn:aws:iam::211125364662:user/kalyan@rafay.co
        type: STANDARD
      authenticationMode: API
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: aws-ebs-csi-driver
      version: latest
    availabilityZones:
    - us-east-1a
    - us-east-1b
    - us-east-1c
    - us-east-1d
    - us-east-1f
    cloudWatch: {}
    managedNodeGroups:
    - amiFamily: Bottlerocket
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3a.xlarge
      maxSize: 2
      minSize: 1
      name: rauto-ngmanaged0
      privateNetworking: true
      spot: false
      version: "1.35"
      volumeEncrypted: false
      volumeType: gp3
    metadata:
      name: rautocdktf-eks-785894
      region: us-east-1
      tags:
        build_num: dev-master-495
        email: automation@rafay.co
        env: automation
        squad: dev
      version: "1.35"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
  type: aws-eks
