apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-797226210
  project: defaultproject
spec:
  blueprintConfig:
    name: default
  cloudCredentials: rauto_586694635
  config:
    accessConfig:
      authenticationMode: CONFIG_MAP
      bootstrapClusterCreatorAdminPermissions: true
    addons:
    - name: vpc-cni
      version: v1.23.2-eksbuild.1
    - name: coredns
      version: v1.13.2-eksbuild.51
    - name: kube-proxy
      version: v1.33.10-eksbuild.49
    addonsConfig: {}
    autoModeConfig: {}
    autoZonalShiftConfig: {}
    deleteProtection:
      enabled: false
    metadata:
      name: rauto-eks-797226210
      region: us-east-1
      tags:
        DeleteBefore: "2026-10-09T19:06:55Z"
        build_num: dev-master-494
        creation_time: "2026-10-09T11:06:55Z"
        email: automation-user@rafay.co
        env: automation
        rauto_launch_timestamp: "1791544015"
        squad: dev
      version: "1.33"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      desiredCapacity: 2
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.medium
      maxSize: 2
      minSize: 2
      name: rauto-cluster-eks-ng
      privateNetworking: true
      version: "1.33"
      volumeSize: 80
      volumeType: gp2
    vpc:
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
      subnets:
        private:
          subnet-06114706579ea10c0:
            id: subnet-06114706579ea10c0
          subnet-0c93348944b797969:
            id: subnet-0c93348944b797969
        public:
          subnet-00afb1bd23c788794:
            id: subnet-00afb1bd23c788794
          subnet-097e192276767658d:
            id: subnet-097e192276767658d
    zonalShiftConfig: {}
  proxyConfig: {}
  type: aws-eks
