apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-aks-331400811
  project: defaultproject
spec:
  blueprintConfig:
    name: default-aks
  cloudCredentials: rauto_879603425
  config:
    kind: aksClusterConfig
    metadata:
      name: rauto-aks-331400811
    spec:
      managedCluster:
        apiVersion: "2025-05-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: rauto-aks-331400811-dns
          enableRBAC: true
          kubernetesVersion: 1.36.3
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
          powerState:
            code: Running
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2025-05-01"
        name: primary
        properties:
          count: 2
          enableAutoScaling: true
          maxCount: 2
          maxPods: 40
          minCount: 2
          mode: System
          orchestratorVersion: 1.36.3
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: qa-automation
  type: aks
