apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: rauto-eks-tf-nr-291291241
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: rauto_724958156
  config:
    addons:
    - name: aws-ebs-csi-driver
      version: latest
    - name: coredns
      version: latest
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    autoZonalShiftConfig:
      allowedWindows:
      - Sat:00:00-Sat:03:00
      blockingAlarms:
      - arn:aws:cloudwatch:us-east-1:211125364662:alarm:rauto-arc-zonal-blocking-alarm-1
      enabled: true
      outcomeAlarms:
      - arn:aws:cloudwatch:us-east-1:211125364662:alarm:rauto-arc-zonal-outcome-alarm-1
    availabilityZones:
    - us-east-1a
    - us-east-1b
    managedNodeGroups:
    - amiFamily: AmazonLinux2023
      asgSuspendProcesses:
      - AZRebalance
      - HealthCheck
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 1
      name: ng-node-repair-291291241
      nodeRepairConfig:
        enabled: true
        maxParallelNodesRepairedPercentage: 20
        maxUnhealthyNodeThresholdPercentage: 30
        nodeRepairConfigOverrides:
        - minRepairWaitTimeMins: 30
          nodeMonitoringCondition: NetworkingReady
          nodeUnhealthyReason: ContainerRuntimeFailed
          repairAction: Replace
        - minRepairWaitTimeMins: 20
          nodeMonitoringCondition: Ready
          nodeUnhealthyReason: ContainerRuntimeFailed
          repairAction: Replace
      privateNetworking: true
      spot: false
      tags:
        nodegroup-tag-test: "82002772"
      version: "1.34"
      volumeEncrypted: false
      volumeSize: 80
      volumeType: gp3
    metadata:
      name: rauto-eks-tf-nr-291291241
      region: us-east-1
      tags:
        email: automation@rafay.co
        env: automation
      version: "1.34"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2023
      asgSuspendProcesses:
      - AlarmNotification
      - ScheduledActions
      desiredCapacity: 1
      disableIMDSv1: false
      disablePodIMDS: false
      ebsOptimized: false
      efaEnabled: false
      enableDetailedMonitoring: false
      instanceType: t3.xlarge
      maxSize: 2
      minSize: 1
      name: ng-asg-self-291291241
      privateNetworking: true
      version: "1.34"
      volumeEncrypted: false
      volumeSize: 80
      volumeType: gp3
    vpc:
      autoAllocateIPv6: false
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      nat:
        gateway: Single
    zonalShiftConfig:
      enabled: true
  type: aws-eks
