apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-bp-aks-1791401925971-ahpl
  project: defaultproject
spec:
  base:
    name: default-aks
    version: 4.3.1
  componentsCriticality:
  - name: rauto-addon-1791401917579-8hdx
  - name: rauto-addon-1791401918371-6qye
  - name: opa-policy
  - name: cost-profile
  costProfile:
    name: rauto-costprofile-1791401921086-5kbo
    version: version-v1
  customAddons:
  - name: rauto-addon-1791401917579-8hdx
    version: v1
  - dependsOn:
    - rauto-addon-1791401917579-8hdx
    name: rauto-addon-1791401918371-6qye
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer: {}
      nodeExporter:
        enabled: true
      prometheusAdapter: {}
      resources:
        limits:
          cpu: 500m
          memory: 1000Mi
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  opaPolicy:
    opaPolicy:
    - name: rauto-policy-1791401919485-aykm
      version: v1
    profile:
      name: default
      version: latest
  placement:
    fleetValues:
    - custom-bp-aks-1791401925971-ahpl
  sharing:
    enabled: true
    projects:
    - name: rauto-project-1791401925971-ahpl
    - name: rauto-project-one-1791401925971-ahpl
  type: custom
  version: v2
  versionState: active
