apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: custom-bp-aks-1791398009153-5b4h
  project: defaultproject
spec:
  base:
    name: default-aks
    version: 4.3.1
  componentsCriticality:
  - name: rauto-addon-1791398000755-g9uy
  - name: rauto-addon-1791398001515-l1jf
  - name: opa-policy
  - name: cost-profile
  costProfile:
    name: rauto-costprofile-1791398004241-al1m
    version: version-v1
  customAddons:
  - name: rauto-addon-1791398000755-g9uy
    version: v1
  - dependsOn:
    - rauto-addon-1791398000755-g9uy
    name: rauto-addon-1791398001515-l1jf
    version: v1
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      helmExporter:
        enabled: true
      kubeStateMetrics:
        enabled: true
      metricsServer: {}
      nodeExporter:
        enabled: true
      prometheusAdapter: {}
      resources:
        limits:
          cpu: 500m
          memory: 1000Mi
  drift:
    action: Deny
    enabled: true
  driftWebhook:
    enabled: true
  namespaceConfig:
    enableSync: true
    syncType: Unmanaged
  opaPolicy:
    opaPolicy:
    - name: rauto-policy-1791398002632-op69
      version: v1
    profile:
      name: default
      version: latest
  placement:
    fleetValues:
    - custom-bp-aks-1791398009153-5b4h
  type: custom
  version: v2
  versionState: active
