apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: optiona-bp4
  project: defaultproject
spec:
  base:
    name: minimal
    version: 4.3.0
  customAddons:
  - name: simple-addon
    version: v1
  - isOptional: true
    name: redis-cache
    version: v1
  - name: nginx-web
    version: v1
  - isOptional: true
    name: hello-addon
    version: v1
  - isOptional: true
    name: abcdefgh
    version: v1
  - isOptional: true
    name: elasticsearchtestaddon1
    version: v1
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableCsiSecretStore: true
    enableLocalStorage: true
    enableMonitoring: true
    enableRookCeph: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  sharing:
    enabled: true
    projects:
    - name: shobhit
  type: custom
  version: v4
  versionState: active
