apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rautocdktf-blueprint-136606
  project: defaultproject
spec:
  base:
    name: default-aks
    version: 4.3.1
  customAddons:
  - name: rautocdktf-addon-136606
    version: v1.0
  defaultAddons:
    enableIngress: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
      metricsServer: {}
      prometheusAdapter: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v2.0
  versionState: active
