apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rauto-bp-tgl-cmp-a-5318
  project: defaultproject
spec:
  base:
    name: default
    version: 4.3.1
  customAddons:
  - name: a-1-5318
    version: v1
  - name: a-2-5318
    version: v1
  - name: a-3-5318
    version: v1
  defaultAddons:
    enableIngress: true
    enableLocalStorage: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
