apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: rauto-blueprint-4310672
  project: defaultproject
spec:
  base:
    name: minimal
    version: 4.3.1
  customAddons:
  - name: rauto-addon-355303
    version: v1
  defaultAddons:
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: v1
  versionState: active
