apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: test-bp-kust
  project: defaultproject
spec:
  base:
    name: default
    version: 4.3.1
  customAddons:
  - name: hello-addon
    version: v1
  - name: kmkkm
    version: v1
  defaultAddons:
    enableIngress: true
    enableLocalStorage: true
    enableMonitoring: true
    monitoring:
      gpuOperator: {}
  driftWebhook:
    enabled: true
  type: custom
  version: b454
  versionState: draft
