apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: demo-2-v3shobhit6
  project: shobhit
spec:
  blueprintConfig:
    name: sj-bp
    optionalAddons:
    - sj-addon1
    version: v2
  cloudCredentials: shobhit_azure
  config:
    kind: aksClusterConfig
    metadata:
      name: demo-2-v3shobhit6
    spec:
      managedCluster:
        apiVersion: "2023-11-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          addonProfiles:
            azureKeyvaultSecretsProvider:
              config:
                enableSecretRotation: "false"
                rotationPollInterval: 2m
              enabled: true
            azurePolicy:
              enabled: true
            httpApplicationRouting:
              enabled: false
          apiServerAccessProfile:
            enablePrivateCluster: true
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: demo-2-v3shobhi4t
          kubernetesVersion: 1.35.0
          networkProfile:
            dnsServiceIP: 10.0.0.10
            loadBalancerSku: standard
            networkPlugin: azure
            networkPluginMode: overlay
            podCidr: 192.168.0.0/16
            serviceCidr: 10.0.0.0/16
          oidcIssuerProfile:
            enabled: true
          powerState:
            code: Running
          securityProfile:
            workloadIdentity:
              enabled: true
        tags:
          email: gautham@rafay.co
          env: dev
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2023-11-01"
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 5
          maxPods: 40
          minCount: 1
          mode: System
          orchestratorVersion: 1.35.0
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B4ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: shobhit-rg
      workloadIdentities:
      - createIdentity: true
        metadata:
          location: centralindia
          name: shobhit-tf-wi-1-uai-909v3
          resourceGroup: shobhit-rg
          tags:
            owner: shobhit
        roleAssignments:
        - name: Key Vault Secrets User
          scope: /subscriptions/a2252eb2-7a25-432b-a5ec-e18eba6f26b1/resourceGroups/shobhit-rg/providers/Microsoft.KeyVault/vaults/shobhitkeyvault2
        serviceAccounts:
        - createAccount: true
          metadata:
            annotations:
              role: dev
            labels:
              department: shobhit
              owner: shobhit
            name: shobhit-tf-wi-1-sa-909v3
            namespace: default
  type: aks
